#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <algorithm>
#include <llvm/IR/LLVMContext.h>
#include <llvm/IR/Module.h>
#include <llvm/Support/raw_ostream.h>
#include <llvm/Support/CommandLine.h>
#include "belit/EvmToIR.hpp"
#include "belit/Z3Verifier.hpp"

using namespace llvm;
using namespace belit;

// Professional LLVM CLI Arguments
static cl::opt<std::string> InputFilename(cl::Positional, cl::desc("<input hex file>"), cl::Required);
static cl::opt<bool> DumpIR("dump-ir", cl::desc("Dump the generated LLVM IR to stdout"));
static cl::opt<bool> Verify("verify", cl::desc("Run the Z3 Formal Verification engine"), cl::init(true));

// Helper function to convert hex string to byte array
std::vector<uint8_t> hexToBytes(const std::string& hex) {
    std::vector<uint8_t> bytes;
    for (unsigned int i = 0; i < hex.length(); i += 2) {
        std::string byteString = hex.substr(i, 2);
        uint8_t byte = (uint8_t) strtol(byteString.c_str(), NULL, 16);
        bytes.push_back(byte);
    }
    return bytes;
}

int main(int argc, char** argv) {
    // Initialize LLVM CLI Parser
    cl::ParseCommandLineOptions(argc, argv, "Belit EVM Formal Verification & Lifter CLI\n");

    std::ifstream inFile(InputFilename);
    if (!inFile.is_open()) {
        std::cerr << "[!] Error: Could not open input file -> " << InputFilename << "\n";
        return 1;
    }

    std::string hexCode((std::istreambuf_iterator<char>(inFile)), std::istreambuf_iterator<char>());
    
    // Clean up hex data (remove '0x' prefix and whitespaces if any)
    if (hexCode.substr(0, 2) == "0x") hexCode = hexCode.substr(2);
    hexCode.erase(std::remove_if(hexCode.begin(), hexCode.end(), ::isspace), hexCode.end());

    std::vector<uint8_t> bytecode = hexToBytes(hexCode);

    std::cout << "[*] Initializing Belit Engine...\n";
    std::cout << "[*] Target File: " << InputFilename << " (" << bytecode.size() << " bytes)\n";

    LLVMContext ctx;
    auto mod = std::make_unique<Module>("BelitModule", ctx);

    // ==========================================
    // STAGE 1: LIFTER (Bytecode -> LLVM IR)
    // ==========================================
    std::cout << "[1/2] Lifting EVM Bytecode to LLVM IR (SSA Form)...\n";
    EvmToIR lifter(ctx, *mod);
    Function* liftedFunc = nullptr;
    try {
        liftedFunc = lifter.liftBytecode(bytecode, "evm_main");
    } catch (const std::exception& e) {
        std::cerr << "[!] Lifting Error: " << e.what() << "\n";
        return 1;
    }

    if (DumpIR) {
        std::cout << "\n--- GENERATED LLVM IR ---\n";
        liftedFunc->print(outs());
        std::cout << "-------------------------\n\n";
    }

    // ==========================================
    // STAGE 2: Z3 FORMAL VERIFICATION
    // ==========================================
    if (Verify) {
        std::cout << "[2/2] Starting Z3 SMT Mathematical Analysis Engine...\n";
        Z3Verifier verifier;
        
        // Pipeline Connection: The LLVM Module generated by the lifter is fed directly into Z3
        VerificationResult result = verifier.verifySafety(mod.get());

        std::cout << "\n=============================================\n";
        std::cout << "             BELIT ANALYSIS RESULT           \n";
        std::cout << "=============================================\n";
        if (result.isSafe) {
            std::cout << "[+] STATUS: SAFE (Mathematically Proven)\n";
            std::cout << "[+] MESSAGE: " << result.message << "\n";
        } else {
            std::cout << "[-] STATUS: VULNERABILITY DETECTED (CRITICAL!)\n";
            std::cout << "[-] MESSAGE: " << result.message << "\n";
            std::cout << "[-] EXPLOIT MODEL (Counter-example):\n    " << result.exploitPath << "\n";
        }
        std::cout << "=============================================\n";
    }

    return 0;
}